version: 2
updates:
  - package-ecosystem: "maven" # Maven package ecosystem
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
